version: 0.1.x.{build}
skip_commits:
  message: /^\(?doc\)?.*/
clone_depth: 10
init:
- SET
- 'echo System architecture: %PLATFORM%'
- 'echo %APPVEYOR_REPO_NAME%'

environment:
  winrm_user: winrm_test_user
  winrm_password: WinRM_test_Pass@w0rd1
  user_cert: c:\projects\ansible-win-msoffice\user.pem
  user_key: c:\projects\ansible-win-msoffice\key.pem
  user_pfx: c:\projects\ansible-win-msoffice\user.pfx
  CYGWIN: winsymlinks:nativestrict

  matrix:
  - TARGET: cygwin64
    CYG_ROOT: C:\cygwin64
    CYG_SETUP: C:\cygwin64\setup-x86_64.exe
    CYG_CACHE: C:\cygwin64\var\cache\setup
    CYG_BASH: C:\cygwin64\bin\sh
    ANSIBLE_VERSION: 2.3.3.0
    ANSIBLE_EXTRA_VARS:
  - TARGET: cygwin64
    CYG_ROOT: C:\cygwin64
    CYG_SETUP: C:\cygwin64\setup-x86_64.exe
    CYG_CACHE: C:\cygwin64\var\cache\setup
    CYG_BASH: C:\cygwin64\bin\sh
    ANSIBLE_VERSION: 2.4.3.0
    ANSIBLE_EXTRA_VARS:
  - TARGET: cygwin64
    CYG_ROOT: C:\cygwin64
    CYG_SETUP: C:\cygwin64\setup-x86_64.exe
    CYG_CACHE: C:\cygwin64\var\cache\setup
    CYG_BASH: C:\cygwin64\bin\sh
    ANSIBLE_VERSION: 2.5.0b2
    ANSIBLE_EXTRA_VARS:
matrix:
  fast_finish: true

install:
# setup winrm
- ps: net user /Y /add $env:winrm_user $env:winrm_password
- ps: net localgroup administrators $env:winrm_user /add
- ps: $env:PATH="C:\OpenSSL-Win64\bin;$env:PATH"
- ps: Import-Module $env:APPVEYOR_BUILD_FOLDER\test\appveyor\WinrmAppveyor.psm1
- ps: New-ClientCertificate $env:winrm_user $env:APPVEYOR_BUILD_FOLDER
- ps: $env:user_cert_thumb = (Import-pfxCertificate -FilePath $env:user_pfx -CertStoreLocation Cert:\LocalMachine\root).Thumbprint
- ps: Import-pfxCertificate -FilePath $env:user_pfx -CertStoreLocation Cert:\LocalMachine\TrustedPeople
- ps: $env:winrm_cert = (New-SelfSignedCertificate -DnsName localhost -CertStoreLocation cert:\localmachine\my).Thumbprint
- ps: winrm create winrm/config/Listener?Address=*+Transport=HTTPS "@{Hostname=`"localhost`";CertificateThumbprint=`"$($env:winrm_cert)`"}"
- ps: winrm set winrm/config/client/auth '@{Basic="true"}'
- ps: winrm set winrm/config/service/auth '@{Basic="true"}'
- ps: winrm set winrm/config/service/auth '@{Certificate="true"}'
- ps: winrm set winrm/config/service/auth '@{CbtHardeningLevel="Strict"}'
- ps: winrm set winrm/config/service '@{AllowUnencrypted="true"}'
- ps: New-WinrmUserCertificateMapping $env:user_cert_thumb
- ps: $env:PATH="C:\Ruby$env:ruby_version\bin;$env:PATH"
- ps: Write-Host $env:PATH
- ps: ($pwd).path
# setup ansible
- cmd: "%CYG_SETUP% -qgnNdO -l %CYG_CACHE% -R %CYG_ROOT% -s http://cygwin.mirror.constant.com -P openssl-devel -P python2-devel -P python3-devel -P curl -P python-jinja -P python-crypto -P python-openssl -P python-setuptools -P git -P libffi-devel"
- cmd: "%CYG_BASH% -lc 'uname -a'"
- cmd: "%CYG_BASH% -lc 'python -m ensurepip'"
- cmd: "%CYG_BASH% -lc 'python3 -m ensurepip'"
- cmd: "%CYG_BASH% -lc 'python3 -m pip install --upgrade pip'"
- cmd: "%CYG_BASH% -lc 'python3 -m pip install pywinrm'"
- cmd: "%CYG_BASH% -lc 'python3 -m pip install ansible==%ANSIBLE_VERSION%'"
- cmd: "%CYG_BASH% -lc 'ansible --version'"
- cmd: "%CYG_BASH% -lc 'echo localhost ansible_user=$winrm_user ansible_password=$winrm_password ansible_connection=winrm'"
- cmd: "%CYG_BASH% -lc 'ls /'"
- cmd: "%CYG_BASH% -lc 'ls -l /cygdrive/c/'"
- cmd: "%CYG_BASH% -lc 'ls -l /cygdrive/c/projects/ansible-win-msoffice'"
- cmd: "%CYG_BASH% -lc pwd"
- cmd: "%CYG_BASH% -lc 'ansible -i /cygdrive/c/projects/ansible-win-msoffice/test/appveyor/inventory -m win_ping -vvv localhost'"
- cmd: "%CYG_BASH% -lc 'mkdir -p /etc/ansible/roles'"
- cmd: "%CYG_BASH% -lc 'cp /cygdrive/c/projects/ansible-win-msoffice/test/appveyor/ansible.cfg /etc/ansible'"
- cmd: "%CYG_BASH% -lc 'cp -R /cygdrive/c/projects/ansible-win-msoffice /etc/ansible/roles/juju4.win-msoffice'"
- ps: |
    $msiPath = "$($env:USERPROFILE)\inspec-2.0.17-1-x64.msi"
    (New-Object Net.WebClient).DownloadFile('https://packages.chef.io/files/stable/inspec/2.0.17/windows/2016/inspec-2.0.17-1-x64.msi', $msiPath)
    cmd /c start /wait msiexec /i $msiPath /q

build: off
test_script:
- cmd: "%CYG_BASH% -lc 'ansible-playbook /cygdrive/c/projects/ansible-win-msoffice/test/integration/default/default.yml --syntax-check'"
- cmd: "%CYG_BASH% -lc 'ansible-playbook -i /cygdrive/c/projects/ansible-win-msoffice/test/appveyor/inventory /cygdrive/c/projects/ansible-win-msoffice/test/integration/default/default.yml -vvv $ANSIBLE_EXTRA_VARS'"

after_test:
- cmd: |
    %CYG_BASH% -lc 'ansible-playbook -i /cygdrive/c/projects/ansible-win-msoffice/test/appveyor/inventory /cygdrive/c/projects/ansible-win-msoffice/test/integration/default/default.yml $ANSIBLE_EXTRA_VARS'
- ps: |
    Get-ChildItem -Path "HKCU:\Software\Microsoft\Office\16.0\Word\Security"
    Get-ChildItem -Path "HKCU:\Software\Microsoft\Office\16.0\Outlook\Security"
    Get-ChildItem -Path "HKCU:\Software\Microsoft\Office\16.0\Excel\Options"
    Get-ChildItem -Path "HKLM:\SOFTWARE\Microsoft\Office\16.0\Common\COM Compatibility\{0002CE02-0000-0000-C000-000000000046}"
    Get-ChildItem -Path "HKLM:\SOFTWARE\Classes\Equation.3"
    Get-ChildItem -Path "HKCR:\WOW6432Node\CLSID\{0002CE02-0000-0000-C000-000000000046}"
    True

on_finish:
# as winrm_user
- ps |
    $securePassword = ConvertTo-SecureString $env:winrm_password -AsPlainText -Force
    $credential = New-Object System.Management.Automation.PSCredential $env:winrm_user, $securePassword
    Start-Process c:\opscode\inspec\bin\inspec.bat -Credential $credential -ArgumentList ("exec https://github.com/juju4/msoffice-baseline/")
    True
# as appveyor user
#- cmd: c:\opscode\inspec\bin\inspec.bat exec https://github.com/juju4/msoffice-baseline/ || exit 0

notifications:
- provider: Email
  to:
  - nobody@nowhere.com
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: false
