---

# https://twitter.com/GossiTheDog/status/932694287480913920
- name: Download test office files
  win_get_url:
    url: "{{ item }}"
    dest: "{{ win_temp_dir }}\\{{ item | win_basename }}"
  with_items:
    - http://owned.lab6.com/~gossi/research/public/cve-2017-11882/calc.doc
    - http://owned.lab6.com/~gossi/research/public/cve-2017-11882/test.doc
  ignore_errors: true

- name: MsOffice trial by Chocolatey installation
  win_chocolatey:
    name: "{{ item }}"
    state: present
    upgrade: no
  with_items:
# 2013
#    - officeproplus2013
# 2016
    - office365business
#    - office365proplus
#    - office365homepremium
#    - microsoft-teams

# https://support.microsoft.com/en-us/help/210565/how-to-use-startup-command-line-switches-to-start-word-2010-word-2007
