---

- name: Ms Office | defined trusted locations path
  win_regedit:
    key: "HKCU:\\Software\\Microsoft\\Office\\{{ win_msoffice_version_reg }}\\{{ item }}\\Security\\Trusted Locations"
    name: Path
    data: "{{ win_msoffice_trustedlocations }}"
    type: expandstring
  with_items:
    - Access
    - Excel
    - Outlook
    - PowerPoint
    - Visio
    - Word

- name: Ms Office | silently disable OLE Package function in Outlook
  win_regedit:
    key: "HKCU:\\Software\\Microsoft\\Office\\{{ win_msoffice_version_reg }}\\Outlook\\Security"
    name: ShowOLEPackageObj
    data: 0
    type: dword

- name: Ms Office | Prevent activation of OLE packages
  win_regedit:
    key: "HKCU:\\Software\\Microsoft\\Office\\{{ win_msoffice_version_reg }}\\{{ item }}\\Security"
    name: PackagerPrompt
    data: "{{ win_msoffice_packagerprompt }}"
    type: dword
  with_items:
    - Access
    - Excel
    - Outlook
    - PowerPoint
    - Visio
    - Word

- name: Ms Office | Update Macro settings
  win_regedit:
    key: "{{ item.k }}"
    name: "{{ item.n }}"
    data: "{{ item.d }}"
    type: dword
  with_items:
    - { k: "HKCU:\\SOFTWARE\\Policies\\Microsoft\\Office\\{{ win_msoffice_version_reg }}\\Word\\Security",
        n: 'VBAWarnings',
        d: "{{ win_msoffice_vbawarnings }}"
      }
    - { k: "HKCU:\\SOFTWARE\\Policies\\Microsoft\\Office\\{{ win_msoffice_version_reg }}\\Word\\Security",
        n: 'blockcontentexecutionfrominternet',
        d: 1
      }
    - { k: "HKCU:\\SOFTWARE\\Policies\\Microsoft\\Office\\{{ win_msoffice_version_reg }}\\Excel\\Security",
        n: 'VBAWarnings',
        d: "{{ win_msoffice_vbawarnings }}"
      }
    - { k: "HKCU:\\SOFTWARE\\Policies\\Microsoft\\Office\\{{ win_msoffice_version_reg }}\\Excel\\Security",
        n: 'blockcontentexecutionfrominternet',
        d: 1
      }
    - { k: "HKCU:\\SOFTWARE\\Policies\\Microsoft\\Office\\{{ win_msoffice_version_reg }}\\Powerpoint\\Security",
        n: 'VBAWarnings',
        d: "{{ win_msoffice_vbawarnings }}"
      }
    - { k: "HKCU:\\SOFTWARE\\Policies\\Microsoft\\Office\\{{ win_msoffice_version_reg }}\\Powerpoint\\Security",
        n: 'blockcontentexecutionfrominternet',
        d: 1
      }
    - { k: "HKCU:\\SOFTWARE\\Policies\\Microsoft\\Office\\{{ win_msoffice_version_reg }}\\Access\\Security",
        n: 'VBAWarnings',
        d: "{{ win_msoffice_vbawarnings }}"
      }
    - { k: "HKCU:\\SOFTWARE\\Policies\\Microsoft\\Office\\{{ win_msoffice_version_reg }}\\Access\\Security",
        n: 'blockcontentexecutionfrominternet',
        d: 1
      }
    - { k: "HKCU:\\SOFTWARE\\Policies\\Microsoft\\Office\\{{ win_msoffice_version_reg }}\\Publisher\\Security",
        n: 'VBAWarnings',
        d: "{{ win_msoffice_vbawarnings }}"
      }
    - { k: "HKCU:\\SOFTWARE\\Policies\\Microsoft\\Office\\{{ win_msoffice_version_reg }}\\Publisher\\Security",
        n: 'blockcontentexecutionfrominternet',
        d: 1
      }
    - { k: "HKCU:\\SOFTWARE\\Policies\\Microsoft\\Office\\{{ win_msoffice_version_reg }}\\Visio\\Security",
        n: 'VBAWarnings',
        d: "{{ win_msoffice_vbawarnings }}"
      }
    - { k: "HKCU:\\SOFTWARE\\Policies\\Microsoft\\Office\\{{ win_msoffice_version_reg }}\\Visio\\Security",
        n: 'blockcontentexecutionfrominternet',
        d: 1
      }

- name: Ms Office | Ensure Protected view is enabled
  win_regedit:
    key: "{{ item.k }}"
    name: "{{ item.n }}"
    data: "{{ item.d }}"
    type: dword
  with_items:
    - { k: "HKCU:\\SOFTWARE\\Microsoft\\Office\\{{ win_msoffice_version_reg }}\\Outlook\\Security",
        n: 'MarkInternalAsUnsafe',
        d: 1
      }
    - { k: "HKCU:\\SOFTWARE\\Policies\\Microsoft\\Office\\{{ win_msoffice_version_reg }}\\Outlook\\Security",
        n: 'MarkInternalAsUnsafe',
        d: 1
      }
    - { k: "HKCU:\\SOFTWARE\\Microsoft\\Office\\{{ win_msoffice_version_reg }}\\Word\\Security\\ProtectedView",
        n: 'DisableAttachementsInPV',
        d: 0
      }
    - { k: "HKCU:\\SOFTWARE\\Microsoft\\Office\\{{ win_msoffice_version_reg }}\\Word\\Security\\ProtectedView",
        n: 'DisableInternetFilesInPV',
        d: 0
      }
    - { k: "HKCU:\\SOFTWARE\\Microsoft\\Office\\{{ win_msoffice_version_reg }}\\Word\\Security\\ProtectedView",
        n: 'DisableUnsafeLocationsInPV',
        d: 0
      }
    - { k: "HKCU:\\SOFTWARE\\Microsoft\\Office\\{{ win_msoffice_version_reg }}\\Excel\\Security\\ProtectedView",
        n: 'DisableAttachementsInPV',
        d: 0
      }
    - { k: "HKCU:\\SOFTWARE\\Microsoft\\Office\\{{ win_msoffice_version_reg }}\\Excel\\Security\\ProtectedView",
        n: 'DisableInternetFilesInPV',
        d: 0
      }
    - { k: "HKCU:\\SOFTWARE\\Microsoft\\Office\\{{ win_msoffice_version_reg }}\\Excel\\Security\\ProtectedView",
        n: 'DisableUnsafeLocationsInPV',
        d: 0
      }
    - { k: "HKCU:\\SOFTWARE\\Microsoft\\Office\\{{ win_msoffice_version_reg }}\\Powerpoint\\Security\\ProtectedView",
        n: 'DisableAttachementsInPV',
        d: 0
      }
    - { k: "HKCU:\\SOFTWARE\\Microsoft\\Office\\{{ win_msoffice_version_reg }}\\Powerpoint\\Security\\ProtectedView",
        n: 'DisableInternetFilesInPV',
        d: 0
      }
    - { k: "HKCU:\\SOFTWARE\\Microsoft\\Office\\{{ win_msoffice_version_reg }}\\Powerpoint\\Security\\ProtectedView",
        n: 'DisableUnsafeLocationsInPV',
        d: 0
      }
#    - { k: '', n: '', d: '' }

- name: Ms Office | Disable DDE - Link auto update
  win_regedit:
    key: "{{ item }}"
    name: DontUpdateLinks
    data: 1
    type: dword
  with_items:
    - "HKCU:\\Software\\Microsoft\\Office\\{{ win_msoffice_version_reg }}\\Word\\Options"
    - "HKCU:\\Software\\Microsoft\\Office\\{{ win_msoffice_version_reg }}\\Word\\Options\\WordMail"
    - "HKCU:\\Software\\Microsoft\\Office\\{{ win_msoffice_version_reg }}\\Excel\\Options"
  when: win_msoffice_disable_dde_updatelink|bool

- name: Ms Office | Disable DDE - OneNote DisableEmbeddedFiles
  win_regedit:
    key: "{{ item }}"
    name: DisableEmbeddedFiles
    data: 1
    type: dword
  with_items:
    - "HKCU:\\Software\\Microsoft\\Office\\{{ win_msoffice_version_reg }}\\OneNote\\Options"
    - "HKCU:\\Software\\Microsoft\\Office\\{{ win_msoffice_version_reg }}\\Word\\Options\\WordMail"
    - "HKCU:\\Software\\Microsoft\\Office\\{{ win_msoffice_version_reg }}\\Excel\\Options"
  when: win_msoffice_disable_dde_embeddedfiles|bool

- name: Ms Office | Disable DDE - Excel extras
  win_regedit:
    key: "HKCU:\\Software\\Microsoft\\Office\\{{ win_msoffice_version_reg }}\\Excel\\Options"
    name: "{{ item.n }}"
    data: "{{ item.d }}"
    type: dword
  with_items:
    - { n: "DDEAllowed", d: 0 }
    - { n: "DDECleaned", d: 1 }
    - { n: "Options", d: 117 }
  when: win_msoffice_disable_dde_excel_extras|bool

- name: Ms Office | Disable DDE - Excel WorkbookLinkWarnings
  win_regedit:
    key: "HKCU:\\Software\\Microsoft\\Office\\{{ win_msoffice_version_reg }}\\Excel\\Security"
    name: "{{ item.n }}"
    data: "{{ item.d }}"
    type: dword
  with_items:
    - { n: "WorkbookLinkWarnings", d: 2 }
  when: win_msoffice_disable_dde_excel_workbooklink|bool

# https://embedi.com/blog/skeleton-closet-ms-office-vulnerability-you-didnt-know-about
# https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2017-11882
# https://support.microsoft.com/en-ca/help/4055535/how-to-disable-equation-editor-3-0
- name: Disable Equation Editor - CVE-2017-11882
  win_regedit:
    key: "{{ item }}"
    name: "Compatibility Flags"
    data: 1024
    type: dword
  with_items:
    - "HKLM:\\SOFTWARE\\Microsoft\\Office\\{{ win_msoffice_version_reg }}\\Common\\COM Compatibility\\{0002CE02-0000-0000-C000-000000000046}"
    - "HKLM:\\SOFTWARE\\Wow6432Node\\Microsoft\\Office\\{{ win_msoffice_version_reg }}\\Common\\COM Compatibility\\{0002CE02-0000-0000-C000-000000000046}"
  when: win_msoffice_disable_equation_editor|bool

- name: Disable Equation Editor - CVE-2017-11882
  win_regedit:
    key: "{{ item }}"
    state: absent
  with_items:
    - 'HKCR:\CLSID\{0002CE02-0000-0000-C000-000000000046}'
    - 'HKCR:\WOW6432Node\CLSID\{0002CE02-0000-0000-C000-000000000046}'
    - 'HKLM:\SOFTWARE\Classes\Equation.3'
  when: win_msoffice_disable_equation_editor|bool
