---

## 1: Enable All Macros, 2: Disable All macros with notification,
## 3: Disable all macros except those digitally signed, 4: Disable all without notification
- name: Update Macro settings for Ms Project
  win_regedit:
    key: "HKCU:\\Software\\Policies\\Microsoft\\Office\\{{ win_msoffice_version_reg }}\\msproject\\security"
    name: VBAWarnings
    data: "{{ win_msoffice_vbawarnings }}"
    type: dword
